name: My Workflow
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Initialize Terraform
      run: terraform init
    - name: Set up SSH
      run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/id_rsa.pub
            touch ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa.pub
            chmod 600 ~/.ssh/id_rsa
    - name: Azure Login
      run: |
            az login --service-principal --tenant "${{ secrets.AZURE_TENANT_ID }}" --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}"
    
    - name: Import Azure Resource Group
      run: terraform import azurerm_resource_group.resgroup /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/coursework-resource
    
    - name: Import Azure Availability Set
      run: terraform import azurerm_availability_set.coursework /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/coursework-resource/providers/Microsoft.Compute/availabilitySets/coursework

    - name: Import Azure Virtual Network
      run: terraform import azurerm_virtual_network.virtualnet /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/coursework-resource/providers/Microsoft.Network/virtualNetworks/virtualNetwork

    - name: Import Azure Public IP
      run: terraform import azurerm_public_ip.ipaddress /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/coursework-resource/providers/Microsoft.Network/publicIPAddresses/publicIp
    
     - name: Import Azure Subnet
       run: terraform import azurerm_subnet.subnet /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/coursework-resource/providers/Microsoft.Network/virtualNetworks/virtualNetwork/subnets/internal
    

    - name: Apply Terraform
      run: terraform apply -auto-approve
    - name: Run Ansible playbook
      run: ansible-playbook -i hosts --private-key=~/.ssh/id_rsa playbook.yml

